### ISSUE TITLE
Dates Come out as Floats?

### ISSUE THREAD

**Issue by ctindel** [dilshod/xlsx2csv#112]
I have an input with 2 columns of dates, the first date works fine but the second date comes out as an integer or a float:

1/13/2014 12/21/2012
7/17/2014 6/30/2014  6:38:00 PM

Comes out as:

01/13/14,41264
07/17/14,41820.776388888888

I've seen other people having this same problem too, like this:

http://superuser.com/a/447143

Is there something I should be doing here?

**Comment by catkfr** [comment]
Hello,

I am having a very similar issue with a file for which I have no control. 

Here is the traceback:
```Traceback (most recent call last):
  File "/Users/xxx/venv/bin/xlsx2csv", line 1013, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/Users/xxx/venv/bin/xlsx2csv", line 197, in convert
    self._convert(sheetid, outfile)
  File "/Users/xxx/venv/bin/xlsx2csv", line 277, in _convert
    sheet.to_csv(writer)
  File "/Users/xxx/venv/bin/xlsx2csv", line 625, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/private/tmp/python-20180629-54171-1obl659/Python-3.7.0/Modules/pyexpat.c", line 280, in CharacterData
  File "/Users/xxx/venv/bin/xlsx2csv", line 687, in handleCharData
    d = datetime.time((t / 3600) % 24, (t / 60) % 60, t % 60)
TypeError: integer argument expected, got float
```
