### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by boooch** [dilshod/xlsx2csv#114]
```
xlsx2csv -s 1 -d tab ext_fields_export-3.xlsx ext_fields_export-3.csv
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 5, in <module>
    pkg_resources.run_script('xlsx2csv==0.7.2', 'xlsx2csv')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg/EGG-INFO/scripts/xlsx2csv", line 867, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg/EGG-INFO/scripts/xlsx2csv", line 182, in convert
    self._convert(sheetid, outfile)
  File "/usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg/EGG-INFO/scripts/xlsx2csv", line 251, in _convert
    sheet.to_csv(writer)
  File "/usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg/EGG-INFO/scripts/xlsx2csv", line 572, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg/EGG-INFO/scripts/xlsx2csv", line 665, in handleStartElement
    self.spans = [int(i) for i in attrs['spans'].split(":")]
ValueError: invalid literal for int() with base 10: '942 1369'
```

easy_install -U xlsx2csv 
Searching for xlsx2csv
Reading http://pypi.python.org/simple/xlsx2csv/
Best match: xlsx2csv 0.7.2
Processing xlsx2csv-0.7.2-py2.6.egg
xlsx2csv 0.7.2 is already the active version in easy-install.pth
Installing xlsx2csv script to /usr/bin

Using /usr/lib/python2.6/site-packages/xlsx2csv-0.7.2-py2.6.egg
Processing dependencies for xlsx2csv
Finished processing dependencies for xlsx2csv

**Comment by boooch** [comment]
[ext_fields_export-3.xlsx](https://github.com/dilshod/xlsx2csv/files/746176/ext_fields_export-3.xlsx)

**Comment by HenrikHolst** [comment]
I encountered the same error today with xlsx2csv.py v0.7.3 on a .xlsx that seams to be a .xls in reality but which the source (Swedish SEC) named as .xlsx. Converting the file with the older xls2csv.py program works just fine so it appears to be more likely a bug in xlsx2csv than in the .xlsx file itself.

`root@sql-sth:~# xlsx2csv.py fi-blanka.xlsx > out
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv.py", line 986, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv.py", line 195, in convert
    self._convert(sheetid, outfile)
  File "/usr/bin/xlsx2csv.py", line 275, in _convert
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv.py", line 622, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/bin/xlsx2csv.py", line 724, in handleStartElement
    self.spans = [int(i) for i in attrs['spans'].split(":")]
ValueError: invalid literal for int() with base 10: '4095 4097'
`

**Comment by HenrikHolst** [comment]
[fi-blanka.xlsx](https://github.com/dilshod/xlsx2csv/files/1782353/fi-blanka.xlsx)

**Comment by dilshod** [comment]
pushed changes to the repo, give it a try

**Comment by HenrikHolst** [comment]
Works beautifully! Thanks.
