### ISSUE TITLE
Crash when --->python xlsx2csv.py --all --escape filename.xlsx 

### ISSUE THREAD

**Issue by doredemo** [dilshod/xlsx2csv#116]
D:\to -commit\dataProcessor>xlsx2csv.py --all --escape 123.xlsx
-------- 1 - Tabelle1
Traceback (most recent call last):
  File "D:\to -commit\dataProcessor\xlsx2csv.py", line 935, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "D:\to -commit\dataProcessor\xlsx2csv.py", line 228, in convert
    self._convert(s['id'], of)
  File "D:\to -commit\dataProcessor\xlsx2csv.py", line 258, in _convert
    sheet.filedata = re.sub(r"(<v>[^<>]+)&#10;([^<>]+</v>)", r"\1\\n\2", re.sub(r"(<v>[^<>]+)&#9;([^<>]+</v>)", r"\1\\t\2", re.sub(r"(<v>[^<>]+)&#13;([^<>]+</v>)", r"\1\\r\2", sheet.filedata)))
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by doredemo** [comment]
line 258 I changed 
sheet.sharedString = re.sub(r"(<v>[^<>]+)&#10;([^<>]+</v>)", r"\1\\n\2", re.sub(r"(<v>[^<>]+)&#9;([^<>]+</v>)", r"\1\\t\2", re.sub(r"(<v>[^<>]+)&#13;([^<>]+</v>)", r"\1\\r\2", str(sheet.sharedString))))
