### ISSUE TITLE
How to Fix error invalid literal for int() with base 10 'c1'

### ISSUE THREAD

**Issue by rakeshravuri** [dilshod/xlsx2csv#150]
I am getting an error "invalid literal for int() with base 10 'c1'" if tried to convert an xlsx file to csv with your provided code. I identified that the second row of an xlsx file is having datetime and because of it I am getting this error and "open_workbook" is not working.
[MedicaidExclusionFile20180315.xlsx](https://github.com/dilshod/xlsx2csv/files/2098649/MedicaidExclusionFile20180315.xlsx)

**Comment by kingram6865** [comment]
I am having a similar issue, but not perhaps for the same reason. I don't know for sure the trigger.

```
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 427, in <module>
    xlsx2csv(args[0], sys.stdout, **kwargs)
  File "/usr/bin/xlsx2csv", line 112, in xlsx2csv
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv", line 260, in to_csv
    self.parser.Parse(self.data)
  File "/usr/bin/xlsx2csv", line 331, in handleStartElement
    self.spans = [int(i) for i in attrs['spans'].split(":")]
ValueError: invalid literal for int() with base 10: '1023 1025'
```
