### ISSUE TITLE
AttributeError: 'str' object has no attribute 'QUOTE_MINIMAL'

### ISSUE THREAD

**Issue by bitaller** [dilshod/xlsx2csv#163]
Hello,
I am trying to convert a simple xlsx to csv. I got the following error. __version__ = "0.7.4" is in use.

Thanks
--- Py script ---
import xlsx2csv
s = r'C:\tmp\new.xlsx'
d = r'c:\tmp\samll2.csv'      
converter = xlsx2csv.Xlsx2csv(s)
converter.convert(d)
--- xlsx file ---
[new.xlsx](https://github.com/dilshod/xlsx2csv/files/2669331/new.xlsx)
--- Error ---
Traceback (most recent call last):

  File "<ipython-input-40-d8b3ddc3586f>", line 1, in <module>
    runfile('C:/Users/Jinjia/Documents/001.Python/100.PythonScripts/untitled0.py', wdir='C:/Users/Jinjia/Documents/001.Python/100.PythonScripts')

  File "C:\Users\Jinjia\Anaconda3\envs\Python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "C:\Users\Jinjia\Anaconda3\envs\Python36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Jinjia/Documents/001.Python/100.PythonScripts/untitled0.py", line 30, in <module>
    converter = xlsx2csv.Xlsx2csv(s)

  File "C:\Users\Jinjia\Anaconda3\envs\Python36\lib\site-packages\xlsx2csv.py", line 153, in __init__
    options.setdefault("quoting", csv.QUOTE_MINIMAL)

AttributeError: 'str' object has no attribute 'QUOTE_MINIMAL'

**Comment by dilshod** [comment]
It seems you have a variable named "csv" in your code, rename it and try again

**Comment by bitaller** [comment]
Thanks for your reply. It is the solution. But I found another issue.
# Py code Py3.6
import xlsx2csv
src = r'C:\tmp\new.xlsx'
des = r'c:\tmp\my.csv'
converter = xlsx2csv.Xlsx2csv(src)
-- Error message
  File "C:\Users\Jinjia\Documents\001.Python\100.PythonScripts\300.PythonCoding\900.Tools\xlsx2csv.py", line 256, in _convert
    outfile = open(outfile, 'w+', encoding=self.options['outputencoding'], newline="")

KeyError: 'outputencoding'

----------------
Following code works well. 
converter = xlsx2csv.Xlsx2csv(src, outputencoding="utf8")

Should I add add new code line in __init__()?
    def __init__(self, xlsxfile, **options):
        options.setdefault("delimiter", ",")
...
        options.setdefault("lineterminator", "\n")
        options.setdefault("outputencoding", "utf-8")  # new code

Thanks
