### ISSUE TITLE
UnicodeEncodeError during convert

### ISSUE THREAD

**Issue by davidkyles** [dilshod/xlsx2csv#171]
Seeing this error during convert in 0.7.5 but not in 0.7.4

Here was my command –
xlsx2csv -s 0 -e myfile.xlsx > myfile.csv

Traceback (most recent call last):
  File "/usr/local/bin/xlsx2csv", line 4, in <module>
    __import__('pkg_resources').run_script('xlsx2csv==0.7.5', 'xlsx2csv')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/xlsx2csv-0.7.5-py2.7.egg/EGG-INFO/scripts/xlsx2csv", line 1130, in <module>
    
  File "/Library/Python/2.7/site-packages/xlsx2csv-0.7.5-py2.7.egg/EGG-INFO/scripts/xlsx2csv", line 259, in convert
    
  File "/Library/Python/2.7/site-packages/xlsx2csv-0.7.5-py2.7.egg/EGG-INFO/scripts/xlsx2csv", line 305, in _convert
    
  File "/Library/Python/2.7/site-packages/xlsx2csv-0.7.5-py2.7.egg/EGG-INFO/scripts/xlsx2csv", line 339, in _parse
    
  File "/Library/Python/2.7/site-packages/xlsx2csv-0.7.5-py2.7.egg/EGG-INFO/scripts/xlsx2csv", line 463, in parse
    
UnicodeEncodeError: 'ascii' codec can't encode characters in position 96-103: ordinal not in range(128)

**Comment by dilshod** [comment]
I will need xlsx file to fix it, can you send it to me?

**Comment by davidkyles** [comment]
Sure thing.  I imagine it is the the links that are the problem.
