### ISSUE TITLE
NameError: global name 'eprint' is not defined

### ISSUE THREAD

**Issue by Achillefs** [dilshod/xlsx2csv#175]
Hey, we are using `xlsx2csv` to import sheets and it generally works fine. 
Recently, while trying to upload a specific sheet we got the following error:

File "/home/rof/.pyenv/versions/2.7.16/bin/xlsx2csv", line 817, in handleCharData
     eprint("Error: potential invalid date format.")
 NameError: global name 'eprint' is not defined

We moved the `eprint` method at the top of the file, and the script worked with only a warning as I assume was intended, but I am not sure if that is a correct solution?

thanks
ac

**Comment by naokikambe** [comment]
same issue:

```
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 803, in handleCharData
    self.data = ("%f" % (float(self.data))).rstrip('0').rstrip('.')
ValueError: could not convert string to float: '#N/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv", line 258, in convert
    self._convert(s['index'], of)
  File "/usr/bin/xlsx2csv", line 318, in _convert
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv", line 732, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/src/ports/python35/python35-3.5.7-1.x86_64/src/Python-3.5.7/Modules/pyexpat.c", line 282, in CharacterData
  File "/usr/bin/xlsx2csv", line 817, in handleCharData
    eprint("Error: potential invalid date format.")
NameError: name 'eprint' is not defined
```
```
$ xlsx2csv --version
0.7.6
```

thanks,

**Comment by andb0t** [comment]
Hi there,

same issue here :/

```
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 803, in handleCharData
    self.data = ("%f" % (float(self.data))).rstrip('0').rstrip('.')
ValueError: could not convert string to float: '#N/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv", line 216, in convert
    self._convert(sheetid, outfile)
  File "/usr/bin/xlsx2csv", line 318, in _convert
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv", line 732, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "../Modules/pyexpat.c", line 272, in CharacterData
  File "/usr/bin/xlsx2csv", line 817, in handleCharData
    eprint("Error: potential invalid date format.")
NameError: name 'eprint' is not defined
```

```
xlsx2csv --version
0.7.5
```

**Comment by dilshod** [comment]
Can someone send me a sample file to reproduce this?

**Comment by andb0t** [comment]
Sure, I created a minimal example with one cell filled only. It seems to be connected (in my case at least) with the formatting of the cell.

```
> xlsx2csv Book1.xlsx
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 803, in handleCharData
    self.data = ("%f" % (float(self.data))).rstrip('0').rstrip('.')
ValueError: could not convert string to float: '#N/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv", line 216, in convert
    self._convert(sheetid, outfile)
  File "/usr/bin/xlsx2csv", line 318, in _convert
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv", line 732, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "../Modules/pyexpat.c", line 272, in CharacterData
  File "/usr/bin/xlsx2csv", line 817, in handleCharData
    eprint("Error: potential invalid date format.")
NameError: name 'eprint' is not defined
```

[Book1.xlsx](https://github.com/dilshod/xlsx2csv/files/6337615/Book1.xlsx)

**Comment by dilshod** [comment]
Hm, I'm getting:
> ./xlsx2csv.py ~/Downloads/Book1.xlsx 
Error: potential invalid date format.
#N/A

On boh python 2 and 3.
What version of xlsx2csv are you using?

**Comment by andb0t** [comment]
You're using the `.py` version, I'm using the binary installed via `apt install xlsx2csv`. Does that make a difference?

**Comment by rbucker** [comment]
> You're using the `.py` version, I'm using the binary installed via `apt install xlsx2csv`. Does that make a difference?

I'm using pop_os (ubuntu) and it was installed with apt install xlsx2csv... it's a `py` and it produced this error. (version 0.7.6)

```
$ file /usr/bin/xlsx2csv
/usr/bin/xlsx2csv: symbolic link to ../share/xlsx2csv/xlsx2csv.py
```

**Comment by Altruist2692** [comment]
I am also facing similar issue. xlsx2csv version 0.7.5. Anybody have any solution for this? Please suggest.
```
Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 803, in handleCharData
    self.data = ("%f" % (float(self.data))).rstrip('0').rstrip('.')
ValueError: could not convert string to float: '#N/A'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/bin/xlsx2csv", line 216, in convert
    self._convert(sheetid, outfile)
  File "/usr/bin/xlsx2csv", line 318, in _convert
    sheet.to_csv(writer)
  File "/usr/bin/xlsx2csv", line 732, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "../Modules/pyexpat.c", line 272, in CharacterData
  File "/usr/bin/xlsx2csv", line 817, in handleCharData
    eprint("Error: potential invalid date format.")
NameError: name 'eprint' is not defined
```
