### ISSUE TITLE
Unsupported file | Hard exit from xlsx written with openpyxl

### ISSUE THREAD

**Issue by fhk** [dilshod/xlsx2csv#188]
When reading files create by [openpyxl](https://openpyxl.readthedocs.io/en/stable/usage.html) the command line below fails:

```
(xlsxbug) ➜  pandasxl xlsx2csv test.xlsx test.csv
Traceback (most recent call last):
  File "/Users/fabion/anaconda3/envs/xlsxbug/bin/xlsx2csv", line 318, in _convert
    sheet.to_csv(writer)
  File "/Users/fabion/anaconda3/envs/xlsxbug/bin/xlsx2csv", line 732, in to_csv
    self.parser.ParseFile(self.filehandle)
TypeError: argument must have 'read' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fabion/anaconda3/envs/xlsxbug/bin/xlsx2csv", line 1129, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/Users/fabion/anaconda3/envs/xlsxbug/bin/xlsx2csv", line 216, in convert
    self._convert(sheetid, outfile)
  File "/Users/fabion/anaconda3/envs/xlsxbug/bin/xlsx2csv", line 320, in _convert
    sheet_file.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

This can be reproduced by the running the following code to create the file (Note the example with data was also tested and produced the same error):

```
from openpyxl import Workbook

def main():
    wb = Workbook()
    wb.save(filename = 'test.xlsx')

if __name__ == '__main__':
    main()
```

**Comment by palatbarg** [comment]
Hello. I have the same problem but I used Xlsx2csv for convert xlsx to csv

`wb=load_workbook('pff.xlsx')
sheet=wb.active
max_row=sheet.max_row
for i in range(1,max_row+1):
    sent=sheet.cell(row=i,column=2).value
    blob = TextBlob(sent)
    roun=round(blob.sentiment.polarity)
    sheet.cell(row=i,column=1).value=roun
    print (roun)    
wb.save('pff.xlsx')
Xlsx2csv("pff.xlsx", outputencoding="utf-8").convert("myfile.csv")`

**Comment by palatbarg** [comment]
Hello. I have the same problem but I used Xlsx2csv for convert xlsx to csv

`wb=load_workbook('pff.xlsx')
sheet=wb.active
max_row=sheet.max_row
for i in range(1,max_row+1):
    sent=sheet.cell(row=i,column=2).value
    blob = TextBlob(sent)
    roun=round(blob.sentiment.polarity)
    sheet.cell(row=i,column=1).value=roun
    print (roun)    
wb.save('pff.xlsx')
Xlsx2csv("pff.xlsx", outputencoding="utf-8").convert("myfile.csv")`

**Comment by palatbarg** [comment]
Hello. I have the same problem but I used Xlsx2csv for convert xlsx to csv

> wb=load_workbook('pff.xlsx')
sheet=wb.active
max_row=sheet.max_row
for i in range(1,max_row+1):
    sent=sheet.cell(row=i,column=2).value
    blob = TextBlob(sent)
    roun=round(blob.sentiment.polarity)
    sheet.cell(row=i,column=1).value=roun
    print (roun)    
wb.save('pff.xlsx')
Xlsx2csv("pff.xlsx", outputencoding="utf-8").convert("myfile.csv")

**Comment by makulatur** [comment]
I encountered the same problem with a file and it turned out the problem was that I was using an old version of xlsx2csv obtained via PIP. The error is due to the following assignment:

`sheet_path = "/xl/" + relationship['target']`

which, in my case, resulted in a `sheet_path` looking like this

`'/xl//xl/worksheets/sheet.xml'`.

Removing the duplicate `/xl/` in the debugger fixed the issue for me.

However, looking at the code in this repo the bug seems to have already been fixed in commit d2e94ea5a184415fa93a31956c07e37ebb12230b, but this hasn't made its way into PyPI yet.

@dilshod: Maybe you can consider a new release?

**Comment by ankur334** [comment]
> I encountered the same problem with a file and it turned out the problem was an old version of xlsx2csv obtained via PIP. The error is due to the following assignment:
> 
> `sheet_path = "/xl/" + relationship['target']`
> 
> which, in my case, resulted in a `sheet_path` looking like this
> 
> `'/xl//xl/worksheets/sheet.xml'`.
> 
> Removing the duplicate `/xl/` in the debugger fixed the issue for me.
> 
> However, looking at the code in this repo the bug seems to have already been fixed in commit [d2e94ea](https://github.com/dilshod/xlsx2csv/commit/d2e94ea5a184415fa93a31956c07e37ebb12230b), but this hasn't made its way into PyPI yet.
> 
> @dilshod: Maybe you can consider a new release?

I have encountered the same problem today. It works fine when we convert excel into the terminal but with python it is showing error for my file. Error is the same which is mentioned by @makulatur . 
@dilshod : Maybe you can consider updating it.
