### ISSUE TITLE
XLSX file reading problem

### ISSUE THREAD

**Issue by ionstudio** [dilshod/xlsx2csv#205]
I can't read the Excel file, Excel itself opens it with a warning about an invalid file, but fixes it and reads it normally.

xlsx2csv only reads a few lines from the file.

I attach the Excel file and the output of the xlsx2csv:

```
root@acc:/var/www xlsx2csv data.xlsx data.csv
Traceback (most recent call last):
  File "/usr/local/bin/xlsx2csv", line 1166, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/local/bin/xlsx2csv", line 221, in convert
    self._convert(sheetid, outfile)
  File "/usr/local/bin/xlsx2csv", line 341, in _convert
    sheet.to_csv(writer)
  File "/usr/local/bin/xlsx2csv", line 766, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/local/bin/xlsx2csv", line 783, in handleCharData
    xfs_numfmt = self.styles.cellXfs[s]
IndexError: list index out of range
```

**Comment by dilshod** [comment]
fixed

**Comment by ionstudio** [comment]
Thanks!

**Comment by ionstudio** [comment]
I can't read the Excel file, Excel itself opens it with a warning about an invalid file, but fixes it and reads it normally.

xlsx2csv only reads a few lines from the file.

I attach the Excel file and the output of the xlsx2csv:

`Traceback (most recent call last):
  File "/usr/local/bin/xlsx2csv", line 1174, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/local/bin/xlsx2csv", line 221, in convert
    self._convert(sheetid, outfile)
  File "/usr/local/bin/xlsx2csv", line 341, in _convert
    sheet.to_csv(writer)
  File "/usr/local/bin/xlsx2csv", line 766, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/local/bin/xlsx2csv", line 936, in handleEndElement
    d[k] = val
IndexError: list assignment index out of range`

[data.xlsx](https://github.com/dilshod/xlsx2csv/files/5544144/data.xlsx)
