### ISSUE TITLE
I encountered a type conversion error

### ISSUE THREAD

**Issue by Gaoyongxian666** [dilshod/xlsx2csv#245]
Error is reported when big numbers are set to date format

     Traceback (most recent call last):
        File "qutils\xlsx2txt\xlsx2csv.py", line 838, in handleCharData
      OverflowError: Python int too large to convert to C int
      
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\xlsx2txt\xlsx2txt.py", line 67, in process
      File "qutils\xlsx2txt\xlsx2txt.py", line 60, in xlsx2txt
      File "qutils\xlsx2txt\xlsx2csv.py", line 281, in convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 352, in _convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 781, in to_csv
      File "C:\A\34\s\Modules\pyexpat.c", line 272, in CharacterData
      File "qutils\xlsx2txt\xlsx2csv.py", line 874, in handleCharData
    qutils.xlsx2txt.xlsx2csv.XlsxValueError: Error: potential invalid date format.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\xlsx2txt\xlsx2csv.py", line 838, in handleCharData
    OverflowError: Python int too large to convert to C int
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\searchthread.py", line 120, in write_temp
      File "qutils\util.py", line 306, in get_text
      File "qutils\xlsx2txt\xlsx2txt.py", line 71, in process
      File "qutils\xlsx2txt\xlsx2txt.py", line 38, in xlsx2txt_win32
      File "qutils\xlsx2txt\xlsx2txt.py", line 60, in xlsx2txt
      File "qutils\xlsx2txt\xlsx2csv.py", line 281, in convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 352, in _convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 781, in to_csv
      File "C:\A\34\s\Modules\pyexpat.c", line 272, in CharacterData
      File "qutils\xlsx2txt\xlsx2csv.py", line 874, in handleCharData
    qutils.xlsx2txt.xlsx2csv.XlsxValueError: Error: potential invalid date format.

#REF! show  Error

    Traceback (most recent call last):
      File "qutils\xlsx2txt\xlsx2csv.py", line 857, in handleCharData
    ValueError: could not convert string to float: '#REF!'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\xlsx2txt\xlsx2txt.py", line 67, in process
      File "qutils\xlsx2txt\xlsx2txt.py", line 60, in xlsx2txt
      File "qutils\xlsx2txt\xlsx2csv.py", line 281, in convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 352, in _convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 781, in to_csv
      File "C:\A\34\s\Modules\pyexpat.c", line 272, in CharacterData
      File "qutils\xlsx2txt\xlsx2csv.py", line 874, in handleCharData
    qutils.xlsx2txt.xlsx2csv.XlsxValueError: Error: potential invalid date format.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\xlsx2txt\xlsx2csv.py", line 857, in handleCharData
    ValueError: could not convert string to float: '#REF!'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "qutils\searchthread.py", line 120, in write_temp
      File "qutils\util.py", line 306, in get_text
      File "qutils\xlsx2txt\xlsx2txt.py", line 71, in process
      File "qutils\xlsx2txt\xlsx2txt.py", line 38, in xlsx2txt_win32
      File "qutils\xlsx2txt\xlsx2txt.py", line 60, in xlsx2txt
      File "qutils\xlsx2txt\xlsx2csv.py", line 281, in convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 352, in _convert
      File "qutils\xlsx2txt\xlsx2csv.py", line 781, in to_csv
      File "C:\A\34\s\Modules\pyexpat.c", line 272, in CharacterData
      File "qutils\xlsx2txt\xlsx2csv.py", line 874, in handleCharData
    qutils.xlsx2txt.xlsx2csv.XlsxValueError: Error: potential invalid date format.

**Comment by Gaoyongxian666** [comment]
Here are some examples.

Thanks.

[could not convert string to float_formula.xls](https://github.com/dilshod/xlsx2csv/files/10172238/could.not.convert.string.to.float_formula.xls)
[could not convert string to float_ref.xlsx](https://github.com/dilshod/xlsx2csv/files/10172239/could.not.convert.string.to.float_ref.xlsx)
[could not convert string to float_str_error.xlsx](https://github.com/dilshod/xlsx2csv/files/10172240/could.not.convert.string.to.float_str_error.xlsx)
[date format.xlsx](https://github.com/dilshod/xlsx2csv/files/10172241/date.format.xlsx)


[could not convert string to float NA.xlsx](https://github.com/dilshod/xlsx2csv/files/10172237/could.not.convert.string.to.float.NA.xlsx)

**Comment by rwspielman** [comment]
this seems to still be broken for #REF!

**Comment by dilshod** [comment]
Sorry, these xlsx files seem to be broken. I can't open them in any application.

**Comment by rwspielman** [comment]
I'll create a reproducible example on Monday

**Comment by rwspielman** [comment]
https://github.com/dilshod/xlsx2csv/blob/76568f79d5b4b5bb23c2496f47ebc9b48720d82a/xlsx2csv.py#L865

Looks like this line should check against a larger list of error values that Excel can raise than just `#N/A` 

```python
self.data not in ['#N/A', '#REF!', '#DIV/0!', '#CALC!', '#NAME!', '#NULL!', '#NUM!', '#SPILL!', '#VALUE!']
```

**Comment by rwspielman** [comment]
[RefErrorExample.xlsx](https://github.com/user-attachments/files/17286442/RefErrorExample.xlsx)
See H1 and I1, they are #REF! errors with formats (date and number)

**Comment by rwspielman** [comment]
@dilshod can you push this change through pypi?

**Comment by dilshod** [comment]
@rwspielman uploaded https://pypi.org/project/xlsx2csv/0.8.4/ version
