### ISSUE TITLE
Hi, please help, what's this problem ? 

### ISSUE THREAD

**Issue by jesseky** [dilshod/xlsx2csv#52]
Traceback (most recent call last):
  File "/usr/local/bin/xlsx2csv", line 550, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "/usr/local/bin/xlsx2csv", line 162, in convert
    self._convert(sheetid, outfile)
  File "/usr/local/bin/xlsx2csv", line 200, in _convert
    sheet.to_csv(writer)
  File "/usr/local/bin/xlsx2csv", line 362, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "/usr/local/bin/xlsx2csv", line 377, in handleCharData
    xfs_numfmt = self.styles.cellXfs[s]
IndexError: list index out of range

**Comment by turicas** [comment]
@jesseky is this problem still happening? If yes, could you please share a link for this sample file?
