### ISSUE TITLE
Can't get it to work in Win 7 - Encoding Problem?

### ISSUE THREAD

**Issue by Komachiro** [dilshod/xlsx2csv#60]
I executed in a Windows command shell the following command: 

python d:\yy\ww\py\lib\site-packages\xlsx2csv.py "D:\yy\ww\XLS2CSV Converter\source\xxx.xlsx" "D:\yy\xxx\XLS2CSV Converter\distination\vv.csv"

and get the following error message:

Traceback (most recent call last):
  File "d:\yy\ww\py\lib\site-packages\xlsx2csv.py", line 847, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "d:\yy\ww\py\lib\site-packages\xlsx2csv.py", line 178, in convert
    self._convert(sheetid, outfile)
  File "d:\yy\ww\py\lib\site-packages\xlsx2csv.py", line 247, in _convert
    sheet.to_csv(writer)
  File "d:\yy\ww\py\lib\site-packages\xlsx2csv.py", line 558, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "d:\yy\ww\py\lib\site-packages\xlsx2csv.py", line 706, in handleEndElement
    self.writer.writerow(d)
UnicodeEncodeError: 'cp932' codec can't encode character '\xd4' in position 215: illegal multibyte sequence

I'm using Python 3.4.0 and xlsx2csv-0.6.1 installed via pip.
What am I doing wrong?

**Comment by dilshod** [comment]
i need a sample file to try it myself

**Comment by Komachiro** [comment]
I have reduced my xlsx file to a very simple one which shows the bug.
How can I send it to you? I don't see at this bugtracker any possibility to upload a file.
If you let me know your email address, I will send it to you.

**Comment by Komachiro** [comment]
I just found on your GitHub home your email address!
I will send the file to this address.
