### ISSUE TITLE
1 extra new line too much every row

### ISSUE THREAD

**Issue by karelv** [dilshod/xlsx2csv#91]
First things first: **Excellent** tool! Just what I need. Thanks.

However when I convert a xlsx to csv the output csv files have every row 2 new-lines.

Using OS = Win7 with WinPython distribution with `Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40)`

I tried to convert the csv-file with `dos2unix` but it reports that there is an error with the conversion...

The test files are here:
https://www.dropbox.com/sh/ibs37fmrsmrga1z/AAAGRd4N9wkolNrOwx5M0eUva?dl=0

When I open the file in notepad I see the correct output, 
in wordpad it shows all data on a single line,
and in Sublime Text I see the empty line.

The command I used is:
`python Scripts\xlsx2csv test_win.xlsx test_win -a`

Any idea?

**Comment by dilshod** [comment]
Try this command:
`python -c "import os; print(os.linesep.__repr__())"`

output should be "\r\n" on windows

**Comment by karelv** [comment]
I dumped the hex-content of the resulting csv file: (http://www.fileformat.info/tool/hexdump.htm)
```
file name: Sheet1.csv
mime type: 

0000-0010:  43 4f 4c 31-2c 43 4f 4c-32 0d 0d 0a-41 31 2c 42  COL1,COL 2...A1,B
0000-001c:  31 0d 0d 0a-41 32 2c 42-32 0d 0d 0a              1...A2,B 2...
```
And you can see that there `0d 0d 0a` as line ending.
This wrong, but I've no idea how to fix it in the script.
I do know that I can fix the resulting csv-file with:
`perl -p -e "s/\x0d\x0d/\x0d/g" Sheet1.csv > y.csv`

```
file name: y.csv
mime type: 

0000-0010:  43 4f 4c 31-2c 43 4f 4c-32 0d 0a 41-31 2c 42 31  COL1,COL 2..A1,B1
0000-0019:  0d 0a 41 32-2c 42 32 0d-0a                       ..A2,B2. .
```

**Comment by karelv** [comment]
@dilshod , Yes, this is the output.

**Comment by dilshod** [comment]
i have committed changes, it should help

**Comment by karelv** [comment]
I downloaded only the `xlsx2csv.py` file directly from github webpage...
When I run it, I got:
```
Traceback (most recent call last):
  File "xlsx2csv.py", line 757, in <module>
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
AttributeError: 'module' object has no attribute 'SIGPIPE'
```

Do I need to add or install something else?

PS. the previous version was "0.7.2".

**Comment by dilshod** [comment]
updated, please give it a try

**Comment by karelv** [comment]
I download as `xlsx2csv_n.py`, now I got:
```
Traceback (most recent call last):
  File "xlsx2csv_n.py", line 856, in <module>
    xlsx2csv.convert(outfile, sheetid)
  File "xlsx2csv_n.py", line 221, in convert
    self._convert(s['id'], of)
  File "xlsx2csv_n.py", line 242, in _convert
    sheet.to_csv(writer)
  File "xlsx2csv_n.py", line 562, in to_csv
    self.parser.ParseFile(self.filehandle)
  File "..\Modules\pyexpat.c", line 459, in EndElement
  File "xlsx2csv_n.py", line 706, in handleEndElement
    self.writer.writerow(d)
TypeError: 'str' does not support the buffer interface
```
Note: please see here my working copy..
https://www.dropbox.com/s/0225yuyoq8gtk63/xlsx2csv_karelv.py?dl=0
However I don't understand it, as I force to use `linetermination` as '\n', but I got 0x0d and 0x0a in the output...

A 2nd thing I was struggling with is that empty rows are skipped.
In the above link I fixed my 2 problems and it works like a charm!

Thanks,
Karel.

**Comment by dilshod** [comment]
thank you Karel, i'll integrate your fixes into the code

**Comment by karelv** [comment]
Thx! I'm not sure my work around with the lineterminator is ok for publishing ... 

Let me know if I can test something for you.

**Comment by karelv** [comment]
I found this http://stackoverflow.com/a/14693848/2491604
So I updated my copy of your script. Please use this when you integrate...
Please find the updated script at the dropbox link or here as attachment. (I had to rename the extension from py to txt)

[xlsx2csv_karelv.py](https://github.com/dilshod/xlsx2csv/files/152942/xlsx2csv_karelv.txt)

In the mean time I added a feature `--timeformat`, as I have a 'time' formatted cell while it contains also the date. This option let you convert the full data&time of time formatted cell (with date info inside).
